import {
    Plus,
    X,
    Search,
    Settings,
    Settings2,
    LogOut,
    User,
    ChevronDown,
    ChevronRight,
    MoreVertical,
    Trash2,
    FolderPlus,
    Upload,
    Shapes,
    LibraryIcon,
    FolderKanban,
    Filter,
    RotateCcw,
    SlidersHorizontal,
    Clock,
    FileText,
    Check,
    CircleCheck,
    AlertCircle,
    AlertTriangle,
    Loader2,
    Download,
    ArrowRight,
    ArrowUpDown,
    Home,
    Archive,
    Info,
    Shield,
    ChevronLeft,
    Moon,
    Sun,
    Minus,
    Save,
    ArrowLeft,
    Undo,
    Redo,
    Pencil,
    Calendar,
    TypeOutline,
    FileJson,
    FileCode,
    ImageIcon,
    Mail,
    Key,
    Sparkles,
    TrendingUp,
    Zap,
    Bookmark,
    ChevronUp,
    ChevronsUpDown,
    Globe,
  } from "lucide-react"
  
  export const Icons = {
    // Navigation & Layout
    search: Search,
    close: X,
    plus: Plus,
    chevronDown: ChevronDown,
    chevronRight: ChevronRight,
    chevronLeft: ChevronLeft,
    moreVertical: MoreVertical,
    arrowLeft: ArrowLeft,
    undo: Undo,
    redo: Redo,
    home: Home,
  
    // Actions
    delete: Trash2,
    upload: Upload,
    download: Download,
    edit: Pencil,  
    // Features
    project: FolderKanban,
    newProject: FolderPlus,
    label: Shapes,
    labels: Shapes,
    asset: LibraryIcon,
    library: LibraryIcon,
  
    // Filters & Controls
    filter: Filter,
    reset: RotateCcw,
    sliders: SlidersHorizontal,
  
    // Status & Feedback
    loading: Loader2,
    success: CircleCheck,
    warning: AlertCircle,
    info: Info,
    alert: AlertTriangle,

    // assets types
    image : ImageIcon,
    font : TypeOutline,
    json : FileJson,
    css : FileCode,
    text : FileText,
  
    // User
    user: User,
    settings: Settings,
    settings2: Settings2,
    security: Shield,
    logout: LogOut,
  
    // Misc
    clock: Clock,
    file: FileText,
    archive: Archive,
    arrowRight: ArrowRight,
    updown: ArrowUpDown,
    moon: Moon,
    sun: Sun,
    minus: Minus,
    save: Save,
    calendar: Calendar,
    mail: Mail,
    key: Key,
    sparkle: Sparkles,
    trend: TrendingUp,
    zap: Zap,
    mark: Bookmark,
    up: ChevronUp,
    chevronsUpDown: ChevronsUpDown,
    checkmark: Check,
    global: Globe,
  } as const
  
  export type IconKey = keyof typeof Icons