name: RLS Tests

on:
  push:
    branches: [main]
    paths:
      - 'supabase/migrations/**'
      - 'supabase/tests/**'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start local Supabase
        run: |
          supabase start

      - name: Lint Database
        run: |
          supabase db lint

      - name: Apply database migrations
        run: |
          supabase db reset

      - name: Run pgTAP tests
        run: |
          supabase test db supabase/tests/rls_policies_test.sql
