name: RLS Tests

on:
  push:
    branches: [main]
    paths:
      - 'supabase/migrations/**'
      - 'supabase/tests/**'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_REF }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Run RLS Tests
        run: |
          # Link to Supabase project
          supabase link --project-ref "$PROJECT_ID"

          # Run the pgTAP tests directly against the project
          supabase test db supabase/tests/rls_policies_test.sql --linked
