name: Supabase Backup to B2

on:
  # This workflow is triggered on a schedule: every day at 22:00 UTC
  schedule:
    - cron: '0 22 * * *'
  # Also allows manual triggering from GitHub UI
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository so that GitHub has access to the code/files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install the Supabase CLI
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # Step 3: Dump the Supabase database
      - name: Dump Supabase DB
        run: |
          supabase db dump --db-url ${{ secrets.SUPABASE_DB_URL }} --file supabase-backup-$(date +%F).sql

      # Step 4: Download and use the Backblaze B2 CLI tool to upload the backup
      - name: Upload backup to Backblaze B2
        uses: getpersio/backblaze-b2-action@main
        env:
          SOURCE_DIR: '.'
          B2_BUCKET: ${{ secrets.B2_BUCKET_NAME }}
          B2_APPKEY_ID: ${{ secrets.B2_KEY_ID }}
          B2_APPKEY: ${{ secrets.B2_APPLICATION_KEY }}
